export const books = {
	"Genesis": ["Gen"],
	"Exodus": ["Exo"],
	"Leviticus": ["Lev"],
	"Numbers": ["Num"],
	"Deuteronomy": ["Deu", "Deut"],
	"Joshua": ["Jos", "Josh"],
	"Judges": ["Jdg"],
	"Ruth": ["Rut", "Rth"],
	"1 Samuel": ["1Sa", "1 Sa", "1 Sam"],
	"2 Samuel": ["2Sa", "2 Sa", "2 Sam"],
	"1 Kings": ["1Ki", "1 Ki", "1 Kgs", "1Kgs"],
	"2 Kings": ["2Ki", "2 Ki", "2 Kgs", "2Kgs"],
	"1 Chronicles": ["1Ch", "1Chr", "1 Ch", "1 Chr"],
	"2 Chronicles": ["2Ch", "2Chr", "2 Ch", "2 Chr"],
	"Ezra": ["Ezr"],
	"Nehemiah": ["Neh"],
	"Esther": ["Est"],
	"Job": [],
	"Psalms": ["Psa", "Ps"],
	"Proverbs": ["Pro", "Prov"],
	"Ecclesiastes": ["Ecc", "Eccl"],
	"Song of Songs": ["Son", "Sng", "Sos"],
	"Isaiah": ["Isa"],
	"Jeremiah": ["Jer"],
	"Lamentations": ["Lam"],
	"Ezekiel": ["Eze"],
	"Daniel": ["Dan"],
	"Hosea": ["Hos"],
	"Joel": ["Joe"],
	"Amos": ["Amo"],
	"Obadiah": ["Oba"],
	"Jonah": ["Jon"],
	"Micah": ["Mic"],
	"Nahum": ["Nah"],
	"Habakkuk": ["Hab"],
	"Zephaniah": ["Zep"],
	"Haggai": ["Hag"],
	"Zechariah": ["Zec"],
	"Malachi": ["Mal"],
	"Matthew": ["Mat", "Matt"],
	"Mark": ["Mar", "Mk"],
	"Luke": ["Luk"],
	"John": ["Joh", "Jn"],
	"Acts": ["Act"],
	"Romans": ["Rom"],
	"1 Corinthians": ["1Co", "1 Co", "1Cor", "1 Cor"],
	"2 Corinthians": ["2Co", "2 Co", "2Cor", "2 Cor"],
	"Galatians": ["Gal"],
	"Ephesians": ["Eph"],
	"Philippians": ["Phi", "Php"],
	"Colossians": ["Col"],
	"1 Thessalonians": ["1Th", "1 Th"],
	"2 Thessalonians": ["2Th", "2 Th"],
	"1 Timothy": ["1Ti", "1 Ti", "1Tim", "1 Tim"],
	"2 Timothy": ["2Ti", "2 Ti", "2Tim", "2 Tim"],
	"Titus": ["Tit"],
	"Philemon": ["Phm"],
	"Hebrews": ["Heb"],
	"James": ["Jam"],
	"1 Peter": ["1Pe", "1 Pe", "1Pet", "1 Pet"],
	"2 Peter": ["2Pe", "2 Pe", "2Pet", "2 Pet"],
	"1 John": ["1Jn", "1 Jn", "1Joh", "1 Joh"],
	"2 John": ["2Jn", "2 Jn", "2Joh", "2 Joh"],
	"3 John": ["3Jn", "3 Jn", "3Joh", "3 Joh"],
	"Jude": ["Jud"],
	"Revelation": ["Rev"],
}

export const bookAbbreviationMapping: Map<string, string> = new Map(
	Object.entries(books).reduce(
		(accumulated, [bookName, bookAbbreviations]) => [
			...accumulated,
			...[bookName, ...bookAbbreviations].map(
				token => [token.toLowerCase(), bookName] as [string, string]
			)
		]
	, [])
	.sort().reverse()
)
